export const LOAD_INGREDIENTS = "LOAD_INGREDIENTS";
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const CHANGE_INGREDIENT = 'CHANGE_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const LOAD_DETAILS = 'LOAD_DETAILS';
export const DELETE_DETAILS = 'DELETE_DETAILS';
export const ORDER_NUMBER = 'ORDER_NUMBER';
export const ORDER_CLEAR = 'ORDER_CLEAR';